version: '3'
services:
  exchange:
    build:
      context: .
      dockerfile: Containerfile
    ports:
    - "3001:8080"
    depends_on:
    - currency
    - history
    - news
  currency:do400
    build:
      context: ../currency
      dockerfile: Containerfile
    ports:
    - "3002:5000"
  history:
    build:
      context: ../history
      dockerfile: Containerfile
    ports:
    - "3003:8080"
  news:
    build:
      context: ../news
      dockerfile: Containerfile
    ports:
    - "3004:5000"

