pipeline {
    agent { node { label "maven" } }
    stages {
        stage ('Test') {
            steps {
                dir('exchange') {
                    sh './mvnw test'
                }
            }
        }
    }

}