pipeline {
    agent { node { label "maven" } }
    stages {
        stage ('Test') {
            steps {
                dir('exchange') {
                    sh './mvnw test'
                }
            }
        }
    }
    post {
        failure {
            mail to: "team@example.com",
                subject: "Pipeline failure",
                body: "The pipeline execution has failed!!"
        }
    }
}