apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange
spec:
  selector:
    matchLabels:
      app: exchange
  replicas: 1
  template:
    metadata:
      labels:
        app: exchange
    spec:
      containers:
        - name: exchange
          image: quay.io/redhattraining/do400-tot-2:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: exchange
  name: exchange
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: exchange
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: exchange
  labels:
    app: exchange
spec:
  to:
    kind: Service
    name: exchange
  port:
    targetPort: 8080

